/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basura;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author USUARIO
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public PanelMapa panelMapa;
    public NewJFrame() {
        init();
    }
    public void init(){
        JButton botonTercerPiso= new JButton();
        botonTercerPiso.setText("3");
        add(botonTercerPiso);
        botonTercerPiso.setBounds(240, 420, 50, 35);
        botonTercerPiso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPisoClicked(evt,3);
            }
        });

            
          
        });
        panelMapa = new PanelMapa();
        jScrollPane1 = new javax.swing.JScrollPane();

        JPanel panel = new JPanel();
	JScrollPane pictureScrollPane = new JScrollPane(panelMapa);
	pictureScrollPane.setPreferredSize(new Dimension(300, 250));
	pictureScrollPane.setViewportBorder(BorderFactory.createLineBorder(Color.black));

	//pictureScrollPane.setColumnHeaderView(columnView);
	//pictureScrollPane.setRowHeaderView(rowView);

	//pictureScrollPane.setCorner(JScrollPane.UPPER_LEFT_CORNER, 
	//				buttonCorner);
	//pictureScrollPane.setCorner(JScrollPane.LOWER_LEFT_CORNER,
	//				new Corner());
	//pictureScrollPane.setCorner(JScrollPane.UPPER_RIGHT_CORNER,
	//				new Corner());
        
       // panel.setLayout(new BoxLayout(this, BoxLayout.X_AXIS));
        panel.add(pictureScrollPane);
        panel.setBorder(BorderFactory.createEmptyBorder(20,20,20,20));
        this.add(panel);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setText("Nodo:");
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(10, 10, 29, 14);

        jTextField2.setEditable(false);
        jTextField2.setText("getDescripcion()");
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(50, 10, 90, 14);

        jCheckBox1.setText("Hay Obstaculo");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(10, 40, 120, 23);

        jCheckBox2.setText("Hay Luz");
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(10, 70, 63, 23);

        jCheckBox3.setText("Nodo Inicio");
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(10, 100, 79, 23);

        jCheckBox4.setSelected(true);
        jCheckBox4.setText("Servicio Ascensor");
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(10, 220, 120, 23);

        jCheckBox5.setSelected(true);
        jCheckBox5.setText("Energia Electrica");
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(10, 250, 110, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 150, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
