/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import domain.Nodo;
import domain.Punto;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class PanelMapa extends javax.swing.JPanel {

    /**
     * Creates new form PanelMapa
     */
    public PanelMapa() {
        //initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar2 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Upgraded_Robot_Sprite.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                .addComponent(jScrollBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar2;
    // End of variables declaration//GEN-END:variables

public void paint(Graphics g){
        super.paint(g);
        Dimension tamanio = getSize();
        setOpaque(false);
        
        //Colocamos el mapa
        ImageIcon imagenFondo = new ImageIcon(getClass().getResource("/imagen/FRSF Planta Baja 12k.png"));        
        //System.out.println("imprime");
        //(System.out.println(tamanio.width+tamanio.height);
        g.drawImage(imagenFondo.getImage(),0,0,tamanio.width, tamanio.height, null);        
        
        Punto puntoHall_108_39_0= new Punto(108, 39, 0);
	Nodo hall_108_39_0 = new Nodo(puntoHall_108_39_0, "HALL");
       
        g.translate(0,tamanio.height);
        g.setColor(Color.RED);
         System.out.println("imprime");
        System.out.println("x"+tamanio.width+"y"+tamanio.height);
        
         System.out.println("imprime circulo");
         
        double b =tamanio.height*(39.0/102.0);
        double a= tamanio.width*(108.0/190.0);
        System.out.println(a+ "b"+b);
        
        g.fillOval((int)a,(int)-b,15,15);
       
         g.setColor(Color.BLUE);
        g.fillOval(190*3,-90*3,15,15);
         g.setColor(Color.BLACK);
        g.fillOval(10,0,15,15);
        
        
    }    

}
